name: Task
description: Create a new task or user story
title: "[Task]: "
labels: ["type:task"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What needs to be done?
      placeholder: Detailed description of the task...
    validations:
      required: true
