name: Check Pylint

on:
  push:
  pull_request:
  workflow_call:
    inputs:
      python-version:
        description: 'Python version to use'
        required: false
        type: string
        default: '3.11'
      additional-steps:
        description: 'Additional steps to run'
        required: false
        type: string
        default: ''

jobs:
  pylint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ inputs['python-version'] }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ inputs['python-version'] }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Analyze code with pylint
        run: |
          files=$(git ls-files '*.py')
          if [ -z "$files" ]; then
            echo "No Python files to lint: exiting."
            exit 0
          fi
          pylint $files

      - name: Run additional steps
        if: ${{ inputs['additional-steps'] != '' }}
        run: ${{ inputs['additional-steps'] }}