name: Create release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
  workflow_call:
    inputs:
      additional-steps:
        description: "Additional steps to run"
        required: false
        type: string
        default: ""

permissions:
  contents: write

jobs:
  create-release:
    name: Release pushed tag
    runs-on: ubuntu-latest
    steps:
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${tag#v}" \
              --generate-notes

      - name: Run additional steps
        if: ${{ inputs['additional-steps'] != '' }}
        run: ${{ inputs['additional-steps'] }}
