name: Deploy Internal Package

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:
  workflow_call:
    inputs:
      python-version:
        description: 'Python version to use'
        required: false
        type: string
        default: '3.11'
      additional-steps:
        description: 'Additional steps to run'
        required: false
        type: string
        default: ''

jobs:
  deploy:
    # runs-on: self-hosted
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bump2version

      - name: Get version type
        id: version
        run: |
          VERSION=$(git describe --tags --abbrev=0)
          echo "version=$VERSION" >> $GITHUB_ENV
          if [[ "$VERSION" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "version_type=patch" >> $GITHUB_ENV
          elif [[ "$VERSION" =~ ^v[0-9]+\.[0-9]+$ ]]; then
            echo "version_type=minor" >> $GITHUB_ENV
          elif [[ "$VERSION" =~ ^v[0-9]+$ ]]; then
            echo "version_type=major" >> $GITHUB_ENV
          fi

      - name: Bump version
        if: env.version_type != 'major'
        run: |
          bump2version patch

      - name: Build Python package
        run: |
          python setup.py sdist bdist_wheel

      - name: Copy package to local directory
        run: |
          REPO_NAME=${{ github.event.repository.name }}
          VERSION=${{ env.version }}
          DEST_DIR="Z:/root/.pipeline/packages/int/$REPO_NAME/$VERSION"
          mkdir -p $DEST_DIR
          cp dist/* $DEST_DIR
        shell: bash