name: Generate Changelog

on:
  push:
    branches:
      - main
  workflow_dispatch:
  workflow_call:
    inputs:
      node-version:
        description: 'Node.js version to use'
        required: false
        type: string
        default: '16'
      additional-steps:
        description: 'Additional steps to run'
        required: false
        type: string
        default: ''

permissions:
  contents: write

jobs:
  generate-changelog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all commit history for a full changelog

      - name: Set up Node.js ${{ inputs['node-version'] }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs['node-version'] }}

      - name: Install dependencies
        run: npm install && npm install -g auto-changelog

      - name: Generate changelog
        run: npm run changelog

      - name: Remove package-lock.json
        run: rm -f package-lock.json

      - name: Commit and push changelog
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add CHANGELOG.md
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m '[DOC] CHANGELOG'
            git push
          else
            echo "No changes to commit"
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Run additional steps
        if: ${{ inputs['additional-steps'] != '' }}
        run: ${{ inputs['additional-steps'] }}
