name: Generate Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:
  workflow_call:
    inputs:
      python-version:
        description: 'Python version to use'
        required: false
        type: string
        default: '3.11'
      additional-steps:
        description: 'Additional steps to run'
        required: false
        type: string
        default: ''

permissions:
  contents: write

jobs:
  generate-documentation:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}/python
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for `mkdocs.yml`
        id: check_files
        run: |
          if [ -f "mkdocs.yml" ]; then
            echo "mkdocs_exists=true" >> $GITHUB_OUTPUT
          else
            echo "mkdocs_exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Set up Python ${{ inputs['python-version'] }}
        if: steps.check_files.outputs.mkdocs_exists == 'true'
        uses: actions/setup-python@v3
        with:
          python-version: ${{ inputs['python-version'] }}

      - name: Install dependencies
        if: steps.check_files.outputs.mkdocs_exists == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocstrings[python] mkdocs-material mkdocs-git-authors-plugin mkdocs-git-revision-date-localized-plugin mkdocs-git-committers-plugin

      - name: Build and deploy documentation
        if: steps.check_files.outputs.mkdocs_exists == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          python -m mkdocs gh-deploy --force

      - name: Run additional steps
        if: ${{ inputs['additional-steps'] != '' }}
        run: ${{ inputs['additional-steps'] }}