name: Set Issue Priority in Project

on:
  issues:
    types: [added_to_project]

jobs:
  set-priority:
    runs-on: ubuntu-latest
    steps:
      - name: Set priority to low
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: actions/github-script@v7
        with:
          script: |
            const projectItems = await github.rest.graphql.query({
              query: `query($owner: String!, $repo: String!, $issue_number: Int!) {
                repository(owner: $owner, name: $repo) {
                  issue(number: $issue_number) {
                    projectItems(first: 1) {
                      nodes {
                        id
                        project {
                          id
                          fields(first: 20) {
                            nodes {
                              ... on ProjectV2SingleSelectField {
                                id
                                name
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }`,
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            });

            const projectItem = projectItems.repository.issue.projectItems.nodes[0];
            const priorityField = projectItem.project.fields.nodes.find(
              field => field.name.toLowerCase() === 'priority' || 
                      field.name.toLowerCase() === 'status'
            );

            if (priorityField) {
              await github.rest.graphql.mutate({
                query: `mutation($project_id: ID!, $item_id: ID!, $field_id: ID!, $option_id: String!) {
                  updateProjectV2ItemFieldValue(
                    input: {
                      projectId: $project_id
                      itemId: $item_id
                      fieldId: $field_id
                      value: { 
                        singleSelectOptionId: $option_id
                      }
                    }
                  ) {
                    projectV2Item {
                      id
                    }
                  }
                }`,
                project_id: projectItem.project.id,
                item_id: projectItem.id,
                field_id: priorityField.id,
                option_id: "Low"
              });
            }
